version: "3"

services:
  app:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.server.production
      args:
        NODE_ENV: production
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      LOG_LEVEL: debug
      API_ENDPOINT: http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard
      CLIENT_ENDPOINT: http://localhost:3000
      # OFFLINE_DEV_ID: true

  mongo:
    image: mongo:6
    # logging:
    #   driver: none
    volumes:
      - ./db_data:/data/db
    ports:
      - "27017:27017"

  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.client.production
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      API_ENDPOINT: http://localhost:8080
