services:
  app:
    container_name: your-spotify-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.server.production
      args:
        NODE_ENV: production
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - ./your_spotify_mongo_db:/data/db

  web:
    container_name: your-spotify-web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.client.production
      args:
        NODE_ENV: production
