version: "3"

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      API_ENDPOINT: http://localhost:8080 # This MUST be included as a valid URL in the spotify dashboard (see below)
      CLIENT_ENDPOINT: http://localhost:3000
      SPOTIFY_PUBLIC: __your_spotify_client_id__
      SPOTIFY_SECRET: __your_spotify_secret__
      CORS: http://localhost:3000
    volumes:
      - ./server/src:/app/src

  mongo:
    image: mongo:4.4.8
    restart: unless-stopped
    volumes:
      - your_spotify_db:/data/db

  web:
    build:
      context: client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - API_ENDPOINT=http://localhost:8080
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public

volumes:
  your_spotify_db:
    external: false
